### ISSUE TITLE
Create a proxy server to act as an API gateway for Anuko Time Tracker

### ISSUE THREAD

**Issue by shaharsol** [tikalk/anuko-time-tracker-proxy#1]
We're using [Anuko Time Tracker](https://www.anuko.com/time_tracker/index.htm) as an organisational time tracker. It's good product but doesn't have an API and therefore we're limited to it's very basic interface. Had we an API we could develop internally some mobile apps to use it, maybe a Slack command, SMS integration, whatever, but there's no API.

So - we want to deploy a node.js server with an API that will act as the client for Anuko Time Tracker. We will execute this node.js proxy server API commands, and it will act as a browser client for the Time Tracker.

Please use express framework.

Please [register a team in their hosted service](https://timetracker.anuko.com/register.php) for development and for being able to understand the detailed requirements: 

The server needs to implement only one method: "track-time". This method will receive login credentials and time tracking parameters, with which you can do a login via [this form](https://timetracker.anuko.com/login.php). And once logged in, it should populate and submit [this form](https://timetracker.anuko.com/time.php) according to the parameters sent.

Please make the server endpoint configurable (we will use our own Anuko installation in production), and the all system deployable to Heroku.

codemill$200

**Comment by shaharsol** [comment]
@KyleCartmell has been assigned to this task.

**Comment by shaharsol** [comment]
Hi @KyleCartmell thanks for working on this, please let me know if you have any questions.

**Comment by shaharsol** [comment]
@KyleCartmell thanks for the pr, didn't expect it so soon... will have time to look at it only tomorrow

**Comment by naidu** [comment]
Any documentation on how to use this feature?
