### ISSUE TITLE
Add a support for additional input parameter to this proxy server

### ISSUE THREAD

**Issue by shaharsol** [tikalk/anuko-time-tracker-proxy#3]
This server is used as a proxy for the [Anuko Time Tracker](https://timetracker.anuko.com), a service without an API which we need an API for. 

This server has a single method `track-time` that was developed against the free hosted version of Anuko. It enables to login to Anuko and submit the `time` form, and expose this behavior via a single HTTP POST, hence making it a sort of an API... 

By default, Anuko required a `project` param when tracking time. It also enables to define `tasks` for each project, and we do use this implementation in production. This server, however, has been developed without support for passing a `task` parameter and we need to add this support.

For development purposes, I have prepared a pre-configured Anuko account, which is setup the same as our production installation with the task as a required field. 

The endpoint is: https://timetracker.anuko.com/login.php
username: ttt-slack-staging
password: 12345678

You'll find a single project inside, and two predefined tasks within this project.

Your task is to make the `track-time` method of this proxy server support the propogation of the `task` param so in essence, the following POST will result in a record inserted to Anuko:

```
curl -X POST -d "login=ttt-slack-staging" -d "password=12345678" -d "project=ttt-slack" -d "task=development" -d "start=09:00" -d "finish=10:00" -d "date=2016-03-01" -d "note=helloworld" https://{domain-of-the-proxy-server}/track-time
```

codemill$20

**Comment by shaharsol** [comment]
Hi @tarikbenmerar pls let me know if anything is not clear enough, and I'll do my best to explain. I think the main work here is to be able to trace the `task_id` from the `task_name` that the user provides as parameter. I noticed anuko render the entire data set as javascript arrays in the page, so it shouldn't be that hard.

**Comment by internetsadboy** [comment]
@shaharsol please let me know if this gets unassigned - thanks

**Comment by tarikbenmerar** [comment]
@shaharsol I was curious about this job but little  busy. So I let it for others if they can get it faster.

**Comment by shaharsol** [comment]
Thanks @tarikbenmerar, I'll unassign you then.

**Comment by shaharsol** [comment]
@internetsadboy you can grab it now from http://codemil.io/task/56ee9589eedb8903003c372f

**Comment by Gagege** [comment]
Thanks @shaharsol. I should have this done later today.

**Comment by Gagege** [comment]
Should I be seeing an entry added to the time report after I successfully run /track-time? I've run it multiple times and I'm not seeing anything in the test account change.

**Comment by shaharsol** [comment]
Not until you make the fix. The `task` field is required and therefore running the proxy against the test account should probably fail.

**Comment by Gagege** [comment]
I see, thanks.

**Comment by shaharsol** [comment]
If you want to see it running as it is you can simply create an account with Anuko, add a project, and then try. It should run. With the test account I provided I configured it to require also `task`

**Comment by Gagege** [comment]
Hopefully this work for you. Let me know what you think.

**Comment by shaharsol** [comment]
I noticed there's no codemill code in the body of the PR. There should be one or you won't be paid when I merge. I suggest you drop this PR and submit another one with that code. You pick it up in the CodeMill developers dashboard.

**Comment by shaharsol** [comment]
@Gagege You already know this code... if you want to take this one: http://codemill.io/task/56f6ba037e64df030099d215

**Comment by yetanotherusera** [comment]
@shaharsol only ids are availabe in `time.php`. Tasks names are not available and therefore using `time.php` is not enough (at least as it is today). I can take a look and change both `time.php` and the proxy if you want to.

**Comment by shaharsol** [comment]
@yetanotherusera I see `task_names = new Array();` followed by a population of this array with tasks names when I view the source of `/time.php`. Don't you see it?

**Comment by yetanotherusera** [comment]
@shaharsol what I wanted to say is that in the source code of `time.php` there is the intention of having the tasks name as you mentioned. but the array is empty : you can double check by dumping the content of `task_names` in the browser javascript console. 
![codemile](https://cloud.githubusercontent.com/assets/935656/14061718/6d7578d8-f387-11e5-8f32-8d2c9739a1a8.png)
