### ISSUE TITLE
A small nodejs scraping task

### ISSUE THREAD

**Issue by shaharsol** [tikalk/anuko-time-tracker-proxy#7]
We had an issue with this project that was fixed by a codemill developer, but apparently the task was not properly defined by us, hence we need to solve the problem in another way.

Please read #3 for detailed explanation.

The solution the developer found was to use Anuko's `/tasks.php` in order to scrape tasks data. However, apparently in our production setup, the page `/tasks.php` is available only for admins, so most users can't use Anuko via this proxy.

I noticed that tasks data is also rendered as JS code into the `/time.php` page. The task is therefore exactly as it defined in #3, only this time there's another requirement which is to modify the solution to use scraping of the `/time.php` page.

codemill$20

**Comment by blitmap** [comment]
Hello again! :smile:

I think I understand this project well.

1) The lines that need to change are these, correct?

  https://github.com/tikalk/anuko-time-tracker-proxy/blob/master/index.js#L32-L39

2) Further above that, is `/projects.php` visible to non-admins?

**Comment by shaharsol** [comment]
@blitmap hi again so good to see you back!
1. Correct
2. Yes, it's visible.
